### ISSUE TITLE
CodeQL query to detect insecure MaxLengthRequest values in ASP.NET applications

### ISSUE THREAD

**Issue by cldrn** [github/security-lab#4]
## Report

ASP.NET applications with large `MaxLengthRequest` are vulnerable to denial of service attacks. The recommended value by Microsoft is  4096 KB (4 MB) so anything larger than that gets flagged as a warning. This checks corresponds to CWE-016 which didn't exist previously in QL and corresponds to common insecure configurations.

This issue is still commonly found in ASP.NET applications and have been related to the mitigations of other CVEs in the past such as:
* MS11-100 (https://docs.microsoft.com/en-us/security-updates/securitybulletins/2011/ms11-100)
* MS14-009 (https://docs.microsoft.com/en-us/security-updates/securitybulletins/2014/ms14-009)
* And possibly others. 

CodeQL query PR: https://github.com/Semmle/ql/pull/2355

**Comment by kevinbackhouse** [comment]
What am I supposed to do here exactly? The query is incredibly basic, but looks like it will work reliably. It looks for a setting named `maxRequestLength` in an XML file like this:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.web>
    <httpRuntime maxRequestLength="255000" />
  </system.web>
</configuration> 
```

The query checks that `maxRequestLength <= 4096`.

**Comment by xcorail** [comment]
Overall Rating: Low
Paid
